---
collections:
  - ansible.posix
  - community.general
  - community.docker

roles:
  - name: geerlingguy.pip
  - name: geerlingguy.docker
  - name: ofersadan85.hardssh
  - name: ofersadan85.rclone_docker_plugin
